# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0002_auto_20171019_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.DateField(null=True),
        ),
    ]
