# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreignDojo', to='dojoninjas.dojos'),
        ),
    ]
