# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0002_auto_20171027_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='got_poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='poke_count',
        ),
        migrations.AddField(
            model_name='poke',
            name='poke_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='poke_give', to='retake.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poke',
            name='poked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_get', to='retake.User'),
        ),
    ]
