# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0003_auto_20171028_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='numberPokes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
