# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt_app', '0002_user_bday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bday',
            new_name='hired',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='wish',
            field=models.ManyToManyField(blank=True, related_name='_user_wish_+', to='pythonbelt_app.User'),
        ),
    ]
