# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt_app', '0003_auto_20171024_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_by', to='pythonbelt_app.User')),
            ],
        ),
    ]
