# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='name',
            new_name='desc',
        ),
    ]
