# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171026_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description_about',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='courses.Course'),
        ),
    ]
