# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171027_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='id',
            field=models.CharField(default=0, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_descrip', to='courses.Course'),
        ),
    ]
