# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0008_user_bday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bday',
            new_name='hired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
