# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0010_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='item',
            name='listed_by',
            field=models.ManyToManyField(related_name='listed_items', to='loginregis_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to='loginregis_app.User'),
        ),
    ]
