# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20171024_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
