# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
